# Generated by Django 3.2.7 on 2021-09-08 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('folder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('file_id', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=50)),
                ('file_path', models.CharField(max_length=128)),
                ('update_time', models.DateTimeField()),
                ('file_type', models.CharField(max_length=32)),
                ('file_size', models.CharField(max_length=16)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_folder', to='folder.folder')),
            ],
        ),
    ]
