# Generated by Django 3.2.7 on 2021-09-10 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0004_file_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='folder',
            new_name='father_folder',
        ),
    ]
