# Generated by Django 3.2.7 on 2021-09-11 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0005_rename_folder_file_father_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='key',
            field=models.CharField(default=1, max_length=1024),
            preserve_default=False,
        ),
    ]
