# Generated by Django 3.2.5 on 2021-09-09 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('folder', '0003_alter_folder_father_folder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='father_folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children_folders', to='folder.folder'),
        ),
    ]
