# Generated by Django 3.2.5 on 2021-09-09 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_auto_20210910_0010'),
        ('folder', '0005_folder_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='folders', to='group.group'),
        ),
    ]
