# Generated by Django 3.2.5 on 2021-09-09 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_delete_profile'),
        ('group', '0002_alter_group_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='folder',
        ),
        migrations.AlterField(
            model_name='group',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_groups', to='account.user'),
        ),
        migrations.AlterField(
            model_name='group',
            name='member',
            field=models.ManyToManyField(related_name='joined_groups', to='account.User'),
        ),
    ]
