# Generated by Django 3.2.7 on 2021-09-10 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_auto_20210910_0010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='member',
            new_name='members',
        ),
    ]
